# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli
      - name: install the Heroku cli
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 17.9.0
      - run: |
          HEROKU_API_KEY=${secrets.HEROKU_API_KEY} heroku git:clone -a ${{secrets.HEROKU_APP_NAME}} dist
          npm install
          npm run clean
          npm run release
          
      - name: deploy
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: generate heroku netrc
        run: |
          cat > /home/runner/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: deploy to heroku
        run: |
          cd dist
          git add .
          git commit -am "Github CI - update"
          git push heroku main
