# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # https://devcenter.heroku.com/articles/heroku-cli#install-the-heroku-cli
      - name: install the Heroku cli
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: upgrade Node to 17.9.0
        uses: actions/setup-node@v3
        with:
          environment: production
          node-version: 17.9.0
      - run: |
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku git:clone -a ts-guestbook dist
          npm install
          npm run clean
          npm run release
          cd dist
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} git add .
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} git commit -am "Github CI - update"
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} git push heroku main

